"""Create initial operational tables

Revision ID: 06c5c2ff4a46
Revises: 
Create Date: 2026-08-06 10:53:25.243927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c5c2ff4a46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_jid', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('price_per_request', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('batch_enabled', sa.Boolean(), nullable=False),
    sa.Column('batch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('batch_max_items', sa.Integer(), nullable=False),
    sa.Column('daily_cutoff_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_cutoff_time', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_whatsapp_jid'), 'clients', ['whatsapp_jid'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('whatsapp_jid', sa.String(length=160), nullable=False),
    sa.Column('evolution_instance', sa.String(length=100), nullable=False),
    sa.Column('response_header', sa.String(length=160), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_whatsapp_jid'), 'providers', ['whatsapp_jid'], unique=True)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('outbound_text', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_client_id'), 'batches', ['client_id'], unique=False)
    op.create_index(op.f('ix_batches_provider_id'), 'batches', ['provider_id'], unique=False)
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=200), nullable=False),
    sa.Column('source_jid', sa.String(length=160), nullable=False),
    sa.Column('sender_jid', sa.String(length=160), nullable=True),
    sa.Column('sender_name', sa.String(length=160), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('original_curp', sa.String(length=18), nullable=True),
    sa.Column('detected_name', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('provider_result', sa.Text(), nullable=True),
    sa.Column('idcif', sa.String(length=32), nullable=True),
    sa.Column('result_code', sa.String(length=40), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_to_provider_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_client_id'), 'requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_requests_original_curp'), 'requests', ['original_curp'], unique=False)
    op.create_index(op.f('ix_requests_provider_id'), 'requests', ['provider_id'], unique=False)
    op.create_index(op.f('ix_requests_rfc'), 'requests', ['rfc'], unique=False)
    op.create_index(op.f('ix_requests_source_jid'), 'requests', ['source_jid'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_whatsapp_message_id'), 'requests', ['whatsapp_message_id'], unique=True)
    op.create_table('batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_items_batch_id'), 'batch_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_items_request_id'), 'batch_items', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_items_request_id'), table_name='batch_items')
    op.drop_index(op.f('ix_batch_items_batch_id'), table_name='batch_items')
    op.drop_table('batch_items')
    op.drop_index(op.f('ix_requests_whatsapp_message_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_source_jid'), table_name='requests')
    op.drop_index(op.f('ix_requests_rfc'), table_name='requests')
    op.drop_index(op.f('ix_requests_provider_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_original_curp'), table_name='requests')
    op.drop_index(op.f('ix_requests_client_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_index(op.f('ix_batches_provider_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_client_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_providers_whatsapp_jid'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_clients_whatsapp_jid'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
