"""Support multiple requests per message

Revision ID: 7949cda999dd
Revises: 06c5c2ff4a46
Create Date: 2026-08-06 11:57:26.030572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7949cda999dd'
down_revision: Union[str, Sequence[str], None] = '06c5c2ff4a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('default_provider_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clients_default_provider_id'), 'clients', ['default_provider_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'providers', ['default_provider_id'], ['id'])
    op.add_column('requests', sa.Column('identifier_key', sa.String(length=18), nullable=False))
    op.alter_column('requests', 'rfc',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.drop_index(op.f('ix_requests_whatsapp_message_id'), table_name='requests')
    op.create_index(op.f('ix_requests_whatsapp_message_id'), 'requests', ['whatsapp_message_id'], unique=False)
    op.create_index(op.f('ix_requests_identifier_key'), 'requests', ['identifier_key'], unique=False)
    op.create_unique_constraint('uq_requests_message_identifier', 'requests', ['whatsapp_message_id', 'identifier_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_requests_message_identifier', 'requests', type_='unique')
    op.drop_index(op.f('ix_requests_identifier_key'), table_name='requests')
    op.drop_index(op.f('ix_requests_whatsapp_message_id'), table_name='requests')
    op.create_index(op.f('ix_requests_whatsapp_message_id'), 'requests', ['whatsapp_message_id'], unique=True)
    op.alter_column('requests', 'rfc',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.drop_column('requests', 'identifier_key')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_default_provider_id'), table_name='clients')
    op.drop_column('clients', 'default_provider_id')
    # ### end Alembic commands ###
