"""Add daily cutoff history

Revision ID: baecd89230aa
Revises: 7949cda999dd
Create Date: 2026-08-06 15:11:56.737079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baecd89230aa'
down_revision: Union[str, Sequence[str], None] = '7949cda999dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_cutoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('rfc_count', sa.Integer(), nullable=False),
    sa.Column('curp_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'period_start', 'period_end', name='uq_daily_cutoffs_client_period')
    )
    op.create_index(op.f('ix_daily_cutoffs_client_id'), 'daily_cutoffs', ['client_id'], unique=False)
    op.create_index(op.f('ix_daily_cutoffs_period_end'), 'daily_cutoffs', ['period_end'], unique=False)
    op.create_index(op.f('ix_daily_cutoffs_period_start'), 'daily_cutoffs', ['period_start'], unique=False)
    op.create_index(op.f('ix_daily_cutoffs_status'), 'daily_cutoffs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_cutoffs_status'), table_name='daily_cutoffs')
    op.drop_index(op.f('ix_daily_cutoffs_period_start'), table_name='daily_cutoffs')
    op.drop_index(op.f('ix_daily_cutoffs_period_end'), table_name='daily_cutoffs')
    op.drop_index(op.f('ix_daily_cutoffs_client_id'), table_name='daily_cutoffs')
    op.drop_table('daily_cutoffs')
    # ### end Alembic commands ###
